"""Add enum status and index

Revision ID: 09ea8743317e
Revises: 6eb0e51187aa
Create Date: 2026-01-26 23:42:36.153385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09ea8743317e"
down_revision: Union[str, None] = "6eb0e51187aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE userstatus AS ENUM ('ACTIVE', 'INACTIVE', 'PENDING', 'DELETED')"
    )

    # Convert existing data to uppercase first
    op.execute("UPDATE users SET status = UPPER(status)")
    op.execute(
        """
        ALTER TABLE users 
        ALTER COLUMN status TYPE userstatus 
        USING status::userstatus
    """
    )
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index
    op.drop_index(op.f("ix_users_status"), table_name="users")

    # Convert back to VARCHAR
    op.execute(
        """
        ALTER TABLE users 
        ALTER COLUMN status TYPE VARCHAR 
        USING status::text
    """
    )

    # Drop the enum type
    op.execute("DROP TYPE userstatus")
    # ### end Alembic commands ###
