"""Add index to event name

Revision ID: 2662a8725a77
Revises: 43f372ab57a0
Create Date: 2026-02-18 21:54:13.909329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2662a8725a77'
down_revision: Union[str, None] = '43f372ab57a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_name'), table_name='events')
    # ### end Alembic commands ###

