"""Add relationship to Memory and Event table

Revision ID: 3bc427fd60e0
Revises: aee170233bdd
Create Date: 2026-01-26 23:58:19.945915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc427fd60e0'
down_revision: Union[str, None] = 'aee170233bdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_memories_visibility'), 'memories', ['visibility'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memories_visibility'), table_name='memories')
    # ### end Alembic commands ###

