"""Add event owner relationship

Revision ID: 43f372ab57a0
Revises: b105da17591c
Create Date: 2026-02-18 21:51:53.979219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43f372ab57a0'
down_revision: Union[str, None] = 'b105da17591c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'events', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_column('events', 'owner_id')
    # ### end Alembic commands ###

