"""Add composite index in Event table

Revision ID: 52b6b4ce74ff
Revises: 09ea8743317e
Create Date: 2026-01-26 23:49:33.660484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b6b4ce74ff'
down_revision: Union[str, None] = '09ea8743317e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_events_group_priority', 'events', ['group_id', 'priority'], unique=False)
    op.create_index('ix_events_group_start_date', 'events', ['group_id', 'start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_group_start_date', table_name='events')
    op.drop_index('ix_events_group_priority', table_name='events')
    # ### end Alembic commands ###

