"""Adding current active group id in User table

Revision ID: 54dcd0d1785e
Revises: c820577ce490
Create Date: 2026-01-31 22:01:20.297389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54dcd0d1785e'
down_revision: Union[str, None] = 'c820577ce490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_group_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_active_group_id'), 'users', ['active_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_active_group_id'), table_name='users')
    op.drop_column('users', 'active_group_id')
    # ### end Alembic commands ###

