"""Add index in owner_id Group table

Revision ID: 6eb0e51187aa
Revises: bbc8f0baf4d0
Create Date: 2026-01-25 23:06:14.365591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb0e51187aa'
down_revision: Union[str, None] = 'bbc8f0baf4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    # ### end Alembic commands ###

