"""Add roles for group members

Revision ID: 7c206b7b748b
Revises: 7cb856923327
Create Date: 2026-06-08 23:15:52.321656

"""

from typing import Sequence, Union

from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7c206b7b748b"
down_revision: Union[str, None] = "7cb856923327"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    grouprole = postgresql.ENUM(
        "owner", "admin", "moderator", "member", name="grouprole"
    )
    grouprole.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "group_members",
        sa.Column(
            "role",
            sa.Enum("owner", "admin", "moderator", "member", name="grouprole"),
            server_default="member",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("group_members", "role")
    grouprole = postgresql.ENUM(
        "owner", "admin", "moderator", "member", name="grouprole"
    )
    grouprole.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
