"""Add unique constraint and index to Tag name column, supress string length

Revision ID: aee170233bdd
Revises: 52b6b4ce74ff
Create Date: 2026-01-26 23:52:02.493909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aee170233bdd'
down_revision: Union[str, None] = '52b6b4ce74ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    # ### end Alembic commands ###

