"""Adding event category

Revision ID: b105da17591c
Revises: 2de35c72fc96
Create Date: 2026-02-18 20:54:18.965994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b105da17591c'
down_revision: Union[str, None] = '2de35c72fc96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    eventcategory_enum = postgresql.ENUM('HANG_OUT', 'DATE', 'BUSINESS', 'COFFEE_HOPPING', 'FOOD_TOUR', 'GAMING', 'MOVIE', 'OTHER', name='eventcategory')
    eventcategory_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('events', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('events', sa.Column('category', sa.Enum('HANG_OUT', 'DATE', 'BUSINESS', 'COFFEE_HOPPING', 'FOOD_TOUR', 'GAMING', 'MOVIE', 'OTHER', name='eventcategory'), nullable=False))
    op.drop_index('ix_events_end_date', table_name='events')
    op.drop_index('ix_events_group_start_date', table_name='events')
    op.drop_index('ix_events_start_date', table_name='events')
    op.create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    op.create_index(op.f('ix_events_end_time'), 'events', ['end_time'], unique=False)
    op.create_index('ix_events_group_start_time', 'events', ['group_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_events_start_time'), 'events', ['start_time'], unique=False)
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('start_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_events_start_time'), table_name='events')
    op.drop_index('ix_events_group_start_time', table_name='events')
    op.drop_index(op.f('ix_events_end_time'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.create_index('ix_events_start_date', 'events', ['start_date'], unique=False)
    op.create_index('ix_events_group_start_date', 'events', ['group_id', 'start_date'], unique=False)
    op.create_index('ix_events_end_date', 'events', ['end_date'], unique=False)
    op.drop_column('events', 'category')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'start_time')
    
    # Drop the enum type
    eventcategory_enum = postgresql.ENUM('HANG_OUT', 'DATE', 'BUSINESS', 'COFFEE_HOPPING', 'FOOD_TOUR', 'GAMING', 'MOVIE', 'OTHER', name='eventcategory')
    eventcategory_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###

