"""Add relationship back populate from comment to user

Revision ID: c820577ce490
Revises: f1cd2b3b0b44
Create Date: 2026-01-27 00:04:42.496798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c820577ce490'
down_revision: Union[str, None] = 'f1cd2b3b0b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

