"""Add relationship from memory table to user table

Revision ID: f1cd2b3b0b44
Revises: 3bc427fd60e0
Create Date: 2026-01-27 00:02:43.557497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cd2b3b0b44'
down_revision: Union[str, None] = '3bc427fd60e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

